version: '3.8'
services:
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=neginDb
      - MONGO_INITDB_ROOT_PASSWORD=Nhd6710
  backend:
    build: ./backend
    ports:
      - "8086:8086"
    environment:
      - MONGODB_URI=mongodb://neginDb:Nhd6710@mongodb:27017/
    depends_on:
      - mongodb

  frontend:
    build: ./frontend/my-app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongodb_data:
